### ISSUE TITLE
Don't run the pipeline on every push 

### ISSUE THREAD

**Issue by fickledogfish** [fickledogfish/unowndex#9]
Change

https://github.com/fickledogfish/unowndex/blob/e23a09cda29e5b6c4b3406c53e9a051ce4a87e8d/.github/workflows/tuist.yml#L3

to

```yml
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
```
